#if GAME_LANGUAGE == LANGUAGE_SPANISH

gText_Birch_Welcome::
	.string "¡Hola! Perdona que te haya\n"
	.string "hecho esperar.\p"
	.string "¡Te doy la bienvenida al fabuloso\n"
	.string "mundo de los Pokémon!\p"
	.string "Me llamo Abedul.\p"
	.string "Pero todo el mundo me llama\n"
	.string "Profesor Abedul.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "El mundo está habitado por\n"
	.string "criaturas llamadas Pokémon.\p"
	.string "Los humanos y los Pokémon vivimos\n"
	.string "juntos. A veces nos lo pasamos bien\l"
	.string "y nos ayudamos unos a otros.\p"
	.string "A veces nos unimos y combatimos\n"
	.string "contra equipos como el nuestro.\p"
	.string "Pero, a pesar de estos vínculos,\n"
	.string "ignoramos mucho sobre los Pokémon.\p"
	.string "De hecho, hay multitud de secretos\n"
	.string "que rodean a los Pokémon.\p"
	.string "En mi afán por descubrirlos, he\n"
	.string "dedicado mi vida a la investigación.\l"
	.string "Eso es lo que hago.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "¿Tú quién eres?$"

gText_Birch_BoyOrGirl::
	.string "¿Eres un chico o una chica?$"

gText_Birch_WhatsYourName::
	.string "Muy bien.\n"
	.string "¿Y cómo te llamas?$"

gText_Birch_SoItsPlayer::
	.string "Así que eres {PLAYER}…$"

gText_Birch_YourePlayer::
	.string "¡Ah, sí, ya me acuerdo!\p"
	.string "Tú te acabas de mudar a mi\n"
	.string "pueblo natal, Villa Raíz.\l"
	.string "¿A que sí?\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Vale, escucha bien lo que te\n"
	.string "voy a decir…\p"
	.string "Tu propia aventura está a punto\n"
	.string "de comenzar.\p"
	.string "Adelante, entra en el mundo de los\n"
	.string "Pokémon: un mundo de ensueño, lleno\l"
	.string "de aventuras y grandes amigos.\p"
	.string "Bueno, ven a verme luego. Te espero\n"
	.string "en mi Laboratorio Pokémon.\p"
	.string "$"

#else

gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Birch.\p"
	.string "But everyone calls me the Pokémon\n"
	.string "Professor.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "To unravel Pokémon mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of Littleroot.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my Pokémon Lab.\p"
	.string "$"

#endif
