@ Contest move effect descriptions
#if GAME_LANGUAGE == LANGUAGE_SPANISH
gText_HighlyAppealingMove::
	.string "Resulta muy llamativo.$"

gText_UserMoreEasilyStartled::
	.string "Tras usarlo, será facil\n"
	.string "que te asusten.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Gusta mucho, pero impide\n"
	.string "seguir participando.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Por más que se use, el JUEZ\n"
	.string "no se aburrirá nunca.$"

gText_AvoidStartledByOthersOnce::
	.string "Puede evitar que\n"
	.string "te asusten una vez.$"

gText_AvoidStartledByOthers::
	.string "Puede evitar\n"
	.string "que te asusten.$"

gText_AvoidStartledByOthersLittle:: @ Unused
	.string "Can avoid being startled\n"
	.string "by others a little.$"

gText_UserLessLikelyStartled:: @ Unused
	.string "After this move, the user is\n"
	.string "less likely to be startled.$"

gText_SlightlyStartleFrontMon:: @ Unused
	.string "Slightly startles the\n"
	.string "Pokémon in front.$"

gText_SlightlyStartleAppealed:: @ Unused
	.string "Slightly startles those\n"
	.string "that have made appeals.$"

gText_StartleAppealedBeforeUser::
	.string "Asusta al Pokémon que se\n"
	.string "ha exhibido antes que tú.$"

gText_StartleAllAppealed::
	.string "Asusta a los Pokémon que\n"
	.string "ya se han exhibido.$"

gText_BadlyStartleFrontMon::
	.string "Aterra al último Pokémon\n"
	.string "que se exhibió.$"

gText_BadlyStartleAppealed::
	.string "Aterra a los que\n"
	.string "ya se han exhibido.$"

gText_StartleAppealedBeforeUser2::
	.string "Asusta al Pokémon que se\n"
	.string "ha exhibido antes que tú.$"

gText_StartleAllAppealed2::
	.string "Asusta a los Pokémon que\n"
	.string "ya se han exhibido.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Hace que el Juez deje de\n"
	.string "prestar atención al resto.$"

gText_StartleMonHasJudgesAttention::
	.string "Asusta más al Pokémon que\n"
	.string "capta la atención del Juez.$"

gText_JamOthersMissesTurn::
	.string "Inhibe a los otros,\n"
	.string "pero pierdes un turno.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Asusta más a los que usaron\n"
	.string "recursos del mismo tipo.$"

gText_BadlyStartleCoolAppeals:: @ Unused
	.string "Badly startles Pokémon\n"
	.string "that made Cool appeals.$"

gText_BadlyStartleBeautyAppeals:: @ Unused
	.string "Badly startles Pokémon\n"
	.string "that made Beauty appeals.$"

gText_BadlyStartleCuteAppeals:: @ Unused
	.string "Badly startles Pokémon\n"
	.string "that made Cute appeals.$"

gText_BadlyStartleSmartAppeals:: @ Unused
	.string "Badly startles Pokémon\n"
	.string "that made Smart appeals.$"

gText_BadlyStartleToughAppeals:: @ Unused
	.string "Badly startles Pokémon\n"
	.string "that made Tough appeals.$"

gText_MakeMonAfterUserNervous:: @ Unused
	.string "Makes one Pokémon after\n"
	.string "the user nervous.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Inquieta a los Pokémon\n"
	.string "que van detrás de ti.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Baja la forma de los que\n"
	.string "se han exhibido.$"

gText_BadlyStartleMonsGoodCondition:: @  Unused
	.string "Badly startles Pokémon in\n"
	.string "good condition.$"

gText_AppealGreatIfPerformedFirst::
	.string "La exhibición es un éxito\n"
	.string "si se es el primero.$"

gText_AppealGreatIfPerformedLast::
	.string "La exhibición es un éxito\n"
	.string "si se es el ultimo.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "La exhibición es tan buena\n"
	.string "como las anteriores.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "La exhibición es tan buena\n"
	.string "como la anterior.$"

gText_AppealBetterLaterItsPerformed::
	.string "Causa mayor impacto cuanto\n"
	.string "más tarde se usa.$"

gText_AppealVariesDependingOnTiming::
	.string "El impacto que tenga varía\n"
	.string "según cuándo se use.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Funciona bien si es del\n"
	.string "mismo tipo que el anterior.$"

gText_WorksWellIfDifferentTypeAsBefore:: @ Unused
	.string "Works well if different in\n"
	.string "type than the one before.$"

gText_AffectedByAppealInFront::
	.string "El éxito dependerá de la\n"
	.string "actuación precedente.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Mejora tu forma y te ayuda\n"
	.string "a mantener la calma.$"

gText_AppealWorksWellIfConditionGood::
	.string "Resulta muy lucido\n"
	.string "si estás en buena forma.$"

gText_NextAppealMadeEarlier::
	.string "En la siguiente ronda, deja\n"
	.string "que te exhibas antes.$"

gText_NextAppealMadeLater::
	.string "En la siguiente ronda, deja\n"
	.string "que te exhibas más tarde.$"

gText_TurnOrderMoreEasilyScrambled:: @ Unused
	.string "Makes the next turn's order\n"
	.string "more easily scrambled.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Altera los turnos en la\n"
	.string "siguiente ronda.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Entusiasma al público\n"
	.string "en cualquier Concurso.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Aterra a todos los Pokémon\n"
	.string "que se han exhibido bien.$"

gText_AppealBestMoreCrowdExcited::
	.string "El lucimiento es mayor si\n"
	.string "el público está entregado.$"

gText_TemporarilyStopCrowdExcited::
	.string "Templa momentáneamente\n"
	.string "el fervor del público.$"


@ Strings for new Summary Screen

gText_FourLine_HighlyAppealingMove::
	.string "A highly appealing\n"
	.string "move.$"

gText_FourLine_UserMoreEasilyStartled::
	.string "After this move,\n"
	.string "the user is\n"
	.string "more easily\n"
	.string "startled.$"

gText_FourLine_GreatAppealButNoMoreToEnd::
	.string "Makes a great\n"
	.string "appeal, but\n"
	.string "allows no\n"
	.string "more to the end.$"

gText_FourLine_UsedRepeatedlyWithoutBoringJudge::
	.string "Can be repeatedly\n"
	.string "used without\n"
	.string "boring the JUDGE.$"

gText_FourLine_AvoidStartledByOthersOnce::
	.string "Can avoid being\n"
	.string "startled\n"
	.string "by others once.$"

gText_FourLine_AvoidStartledByOthers::
	.string "Can avoid being\n"
	.string "startled\n"
	.string "by others.$"

gText_FourLine_AvoidStartledByOthersLittle::
	.string "Can avoid being\n"
	.string "startled\n"
	.string "by others a little.$"

gText_FourLine_UserLessLikelyStartled::
	.string "After this move,\n"
	.string "the user is less\n"
	.string "likely to\n"
	.string "be startled.$"

gText_FourLine_SlightlyStartleFrontMon::
	.string "Slightly startles\n"
	.string "the POKéMON\n"
	.string "in front.$"

gText_FourLine_SlightlyStartleAppealed::
	.string "Slightly startles\n"
	.string "those that have\n"
	.string "made appeals.$"

gText_FourLine_StartleAppealedBeforeUser::
	.string "Startles the\n"
	.string "POKéMON that\n"
	.string "appealed before\n"
	.string "the user.$"

gText_FourLine_StartleAllAppealed::
	.string "Startles all\n"
	.string "POKéMON that\n"
	.string "have done\n"
	.string "their appeals.$"

gText_FourLine_BadlyStartleFrontMon::
	.string "Badly startles\n"
	.string "the POKéMON\n"
	.string "in front.$"

gText_FourLine_BadlyStartleAppealed::
	.string "Badly startles\n"
	.string "those that\n"
	.string "have made appeals.$"

gText_FourLine_StartleAppealedBeforeUser2::
	.string "Startles the\n"
	.string "POKéMON that\n"
	.string "appealed before\n"
	.string "the user.$"

gText_FourLine_StartleAllAppealed2::
	.string "Startles all\n"
	.string "POKéMON that\n"
	.string "have done\n"
	.string "their appeals.$"

gText_FourLine_ShiftJudgesAttentionFromOthers::
	.string "Shifts the\n"
	.string "JUDGE's attention\n"
	.string "from others.$"

gText_FourLine_StartleMonHasJudgesAttention::
	.string "Startles the\n"
	.string "POKéMON that\n"
	.string "has the\n"
	.string "JUDGE's attention.$"

gText_FourLine_JamOthersMissesTurn::
	.string "Jams the others,\n"
	.string "and misses one\n"
	.string "turn of appeals.$"

gText_FourLine_StartleMonsMadeSameTypeAppeal::
	.string "Startles POKéMON\n"
	.string "that made a\n"
	.string "same-type appeal.$"

gText_FourLine_BadlyStartleCoolAppeals::
	.string "Badly startles\n"
	.string "POKéMON\n"
	.string "that made\n"
	.string "COOL appeals.$"

gText_FourLine_BadlyStartleBeautyAppeals::
	.string "Badly startles\n"
	.string "POKéMON\n"
	.string "that made\n"
	.string "BEAUTY appeals.$"

gText_FourLine_BadlyStartleCuteAppeals::
	.string "Badly startles\n"
	.string "POKéMON\n"
	.string "that made\n"
	.string "CUTE appeals.$"

gText_FourLine_BadlyStartleSmartAppeals::
	.string "Badly startles\n"
	.string "POKéMON\nthat made\n"
	.string "SMART appeals.$"

gText_FourLine_BadlyStartleToughAppeals::
	.string "Badly startles\n"
	.string "POKéMON\n"
	.string "that made\n"
	.string "TOUGH appeals.$"

gText_FourLine_MakeMonAfterUserNervous::
	.string "Makes one\n"
	.string "POKéMON after\n"
	.string "the user nervous.$"

gText_FourLine_MakeAllMonsAfterUserNervous::
	.string "Makes all\n"
	.string "POKéMON after\n"
	.string "the user nervous.$"

gText_FourLine_WorsenConditionOfThoseMadeAppeals::
	.string "Worsens the\n"
	.string "condition of\n"
	.string "those that\n"
	.string "made appeals.$"

gText_FourLine_BadlyStartleMonsGoodCondition::
	.string "Badly startles\n"
	.string "POKéMON in\n"
	.string "good condition.$"

gText_FourLine_AppealGreatIfPerformedFirst::
	.string "The appeal works\n"
	.string "great if\n"
	.string "performed first.$"

gText_FourLine_AppealGreatIfPerformedLast::
	.string "The appeal works\n"
	.string "great if\n"
	.string "performed last.$"

gText_FourLine_AppealAsGoodAsThoseBeforeIt::
	.string "Makes the appeal\n"
	.string "as good as\n"
	.string "those before it.$"

gText_FourLine_AppealAsGoodAsOneBeforeIt::
	.string "Makes the appeal\n"
	.string "as good as the\n"
	.string "one before it.$"

gText_FourLine_AppealBetterLaterItsPerformed::
	.string "The appeal\n"
	.string "works better\n"
	.string "the later\n"
	.string "it is performed.$"

gText_FourLine_AppealVariesDependingOnTiming::
	.string "The appeal's\n"
	.string "quality varies\n"
	.string "depending on\n"
	.string "its timing.$"

gText_FourLine_WorksWellIfSameTypeAsBefore::
	.string "Works well if\n"
	.string "it's the same\n"
	.string "type as the\n"
	.string "one before.$"

gText_FourLine_WorksWellIfDifferentTypeAsBefore::
	.string "Works well if\n"
	.string "different in\n"
	.string "type than the\n"
	.string "one before.$"

gText_FourLine_AffectedByAppealInFront::
	.string "Affected by\n"
	.string "how well the\n"
	.string "appeal in\n"
	.string "front goes.$"

gText_FourLine_UpsConditionHelpsPreventNervousness::
	.string "Ups the\n"
	.string "user's condition.\n"
	.string "Helps prevent\n"
	.string "nervousness.$"

gText_FourLine_AppealWorksWellIfConditionGood::
	.string "The appeal works\n"
	.string "well if the\n"
	.string "user's condition\n"
	.string "is good.$"

gText_FourLine_NextAppealMadeEarlier::
	.string "The next appeal\n"
	.string "can be\n"
	.string "made earlier\n"
	.string "next turn.$"

gText_FourLine_NextAppealMadeLater::
	.string "The next appeal\n"
	.string "can be\n"
	.string "made later\n"
	.string "next turn.$"

gText_FourLine_TurnOrderMoreEasilyScrambled::
	.string "Makes the next\n"
	.string "turn's order\n"
	.string "more easily\n"
	.string "scrambled.$"

gText_FourLine_ScrambleOrderOfNextAppeals::
	.string "Scrambles the\n"
	.string "order of\n"
	.string "appeals on\n"
	.string "the next turn.$"

gText_FourLine_AppealExcitesAudienceInAnyContest::
	.string "An appeal that\n"
	.string "excites the\n"
	.string "audience in\n"
	.string "any CONTEST.$"

gText_FourLine_BadlyStartlesMonsGoodAppeals::
	.string "Badly startles\n"
	.string "all POKéMON\n"
	.string "that made\n"
	.string "good appeals.$"

gText_FourLine_AppealBestMoreCrowdExcited::
	.string "The appeal\n"
	.string "works best the\n"
	.string "more the crowd\n"
	.string "is excited.$"

gText_FourLine_TemporarilyStopCrowdExcited::
	.string "Temporarily\n"
	.string "stops the\n"
	.string "crowd from\n"
	.string "growing excited.$"
#else
gText_HighlyAppealingMove::
	.string "A highly appealing move.$"

gText_UserMoreEasilyStartled::
	.string "After this move, the user is\n"
	.string "more easily startled.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Makes a great appeal, but\n"
	.string "allows no more to the end.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Can be repeatedly used\n"
	.string "without boring the Judge.$"

gText_AvoidStartledByOthersOnce::
	.string "Can avoid being startled\n"
	.string "by others once.$"

gText_AvoidStartledByOthers::
	.string "Can avoid being startled\n"
	.string "by others.$"

gText_AvoidStartledByOthersLittle::
	.string "Can avoid being startled\n"
	.string "by others a little.$"

gText_UserLessLikelyStartled::
	.string "After this move, the user is\n"
	.string "less likely to be startled.$"

gText_SlightlyStartleFrontMon::
	.string "Slightly startles the\n"
	.string "Pokémon in front.$"

gText_SlightlyStartleAppealed::
	.string "Slightly startles those\n"
	.string "that have made appeals.$"

gText_StartleAppealedBeforeUser::
	.string "Startles the Pokémon that\n"
	.string "appealed before the user.$"

gText_StartleAllAppealed::
	.string "Startles all Pokémon that\n"
	.string "have done their appeals.$"

gText_BadlyStartleFrontMon::
	.string "Badly startles the\n"
	.string "Pokémon in front.$"

gText_BadlyStartleAppealed::
	.string "Badly startles those that\n"
	.string "have made appeals.$"

gText_StartleAppealedBeforeUser2::
	.string "Startles the Pokémon that\n"
	.string "appealed before the user.$"

gText_StartleAllAppealed2::
	.string "Startles all Pokémon that\n"
	.string "have done their appeals.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Shifts the Judge's\n"
	.string "attention from others.$"

gText_StartleMonHasJudgesAttention::
	.string "Startles the Pokémon that\n"
	.string "has the Judge's attention.$"

gText_JamOthersMissesTurn::
	.string "Jams the others, and misses\n"
	.string "one turn of appeals.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Startles Pokémon that\n"
	.string "made a same-type appeal.$"

gText_BadlyStartleCoolAppeals::
	.string "Badly startles Pokémon\n"
	.string "that made Cool appeals.$"

gText_BadlyStartleBeautyAppeals::
	.string "Badly startles Pokémon\n"
	.string "that made Beauty appeals.$"

gText_BadlyStartleCuteAppeals::
	.string "Badly startles Pokémon\n"
	.string "that made Cute appeals.$"

gText_BadlyStartleSmartAppeals::
	.string "Badly startles Pokémon\n"
	.string "that made Smart appeals.$"

gText_BadlyStartleToughAppeals::
	.string "Badly startles Pokémon\n"
	.string "that made Tough appeals.$"

gText_MakeMonAfterUserNervous::
	.string "Makes one Pokémon after\n"
	.string "the user nervous.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Makes all Pokémon after\n"
	.string "the user nervous.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Worsens the condition of\n"
	.string "those that made appeals.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Badly startles Pokémon in\n"
	.string "good condition.$"

gText_AppealGreatIfPerformedFirst::
	.string "The appeal works great if\n"
	.string "performed first.$"

gText_AppealGreatIfPerformedLast::
	.string "The appeal works great if\n"
	.string "performed last.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Makes the appeal as good\n"
	.string "as those before it.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Makes the appeal as good\n"
	.string "as the one before it.$"

gText_AppealBetterLaterItsPerformed::
	.string "The appeal works better\n"
	.string "the later it is performed.$"

gText_AppealVariesDependingOnTiming::
	.string "The appeal's quality varies\n"
	.string "depending on its timing.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Works well if it's the same\n"
	.string "type as the one before.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Works well if different in\n"
	.string "type than the one before.$"

gText_AffectedByAppealInFront::
	.string "Affected by how well the\n"
	.string "appeal in front goes.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Ups the user's condition.\n"
	.string "Helps prevent nervousness.$"

gText_AppealWorksWellIfConditionGood::
	.string "The appeal works well if the\n"
	.string "user's condition is good.$"

gText_NextAppealMadeEarlier::
	.string "The next appeal can be\n"
	.string "made earlier next turn.$"

gText_NextAppealMadeLater::
	.string "The next appeal can be\n"
	.string "made later next turn.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Makes the next turn's order\n"
	.string "more easily scrambled.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Scrambles the order of\n"
	.string "appeals on the next turn.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "An appeal that excites the\n"
	.string "audience in any Contest.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Badly startles all Pokémon\n"
	.string "that made good appeals.$"

gText_AppealBestMoreCrowdExcited::
	.string "The appeal works best the\n"
	.string "more the crowd is excited.$"

gText_TemporarilyStopCrowdExcited::
	.string "Temporarily stops the\n"
	.string "crowd from growing excited.$"


@ Strings for new Summary Screen

gText_FourLine_HighlyAppealingMove::
	.string "A highly appealing\n"
	.string "move.$"

gText_FourLine_UserMoreEasilyStartled::
	.string "After this move,\n"
	.string "the user is\n"
	.string "more easily\n"
	.string "startled.$"

gText_FourLine_GreatAppealButNoMoreToEnd::
	.string "Makes a great\n"
	.string "appeal, but\n"
	.string "allows no\n"
	.string "more to the end.$"

gText_FourLine_UsedRepeatedlyWithoutBoringJudge::
	.string "Can be repeatedly\n"
	.string "used without\n"
	.string "boring the JUDGE.$"

gText_FourLine_AvoidStartledByOthersOnce::
	.string "Can avoid being\n"
	.string "startled\n"
	.string "by others once.$"

gText_FourLine_AvoidStartledByOthers::
	.string "Can avoid being\n"
	.string "startled\n"
	.string "by others.$"

gText_FourLine_AvoidStartledByOthersLittle::
	.string "Can avoid being\n"
	.string "startled\n"
	.string "by others a little.$"

gText_FourLine_UserLessLikelyStartled::
	.string "After this move,\n"
	.string "the user is less\n"
	.string "likely to\n"
	.string "be startled.$"

gText_FourLine_SlightlyStartleFrontMon::
	.string "Slightly startles\n"
	.string "the POKéMON\n"
	.string "in front.$"

gText_FourLine_SlightlyStartleAppealed::
	.string "Slightly startles\n"
	.string "those that have\n"
	.string "made appeals.$"

gText_FourLine_StartleAppealedBeforeUser::
	.string "Startles the\n"
	.string "POKéMON that\n"
	.string "appealed before\n"
	.string "the user.$"

gText_FourLine_StartleAllAppealed::
	.string "Startles all\n"
	.string "POKéMON that\n"
	.string "have done\n"
	.string "their appeals.$"

gText_FourLine_BadlyStartleFrontMon::
	.string "Badly startles\n"
	.string "the POKéMON\n"
	.string "in front.$"

gText_FourLine_BadlyStartleAppealed::
	.string "Badly startles\n"
	.string "those that\n"
	.string "have made appeals.$"

gText_FourLine_StartleAppealedBeforeUser2::
	.string "Startles the\n"
	.string "POKéMON that\n"
	.string "appealed before\n"
	.string "the user.$"

gText_FourLine_StartleAllAppealed2::
	.string "Startles all\n"
	.string "POKéMON that\n"
	.string "have done\n"
	.string "their appeals.$"

gText_FourLine_ShiftJudgesAttentionFromOthers::
	.string "Shifts the\n"
	.string "JUDGE's attention\n"
	.string "from others.$"

gText_FourLine_StartleMonHasJudgesAttention::
	.string "Startles the\n"
	.string "POKéMON that\n"
	.string "has the\n"
	.string "JUDGE's attention.$"

gText_FourLine_JamOthersMissesTurn::
	.string "Jams the others,\n"
	.string "and misses one\n"
	.string "turn of appeals.$"

gText_FourLine_StartleMonsMadeSameTypeAppeal::
	.string "Startles POKéMON\n"
	.string "that made a\n"
	.string "same-type appeal.$"

gText_FourLine_BadlyStartleCoolAppeals::
	.string "Badly startles\n"
	.string "POKéMON\n"
	.string "that made\n"
	.string "COOL appeals.$"

gText_FourLine_BadlyStartleBeautyAppeals::
	.string "Badly startles\n"
	.string "POKéMON\n"
	.string "that made\n"
	.string "BEAUTY appeals.$"

gText_FourLine_BadlyStartleCuteAppeals::
	.string "Badly startles\n"
	.string "POKéMON\n"
	.string "that made\n"
	.string "CUTE appeals.$"

gText_FourLine_BadlyStartleSmartAppeals::
	.string "Badly startles\n"
	.string "POKéMON\n"
	.string "that made\n"
	.string "SMART appeals.$"

gText_FourLine_BadlyStartleToughAppeals::
	.string "Badly startles\n"
	.string "POKéMON\n"
	.string "that made\n"
	.string "TOUGH appeals.$"

gText_FourLine_MakeMonAfterUserNervous::
	.string "Makes one\n"
	.string "POKéMON after\n"
	.string "the user nervous.$"

gText_FourLine_MakeAllMonsAfterUserNervous::
	.string "Makes all\n"
	.string "POKéMON after\n"
	.string "the user nervous.$"

gText_FourLine_WorsenConditionOfThoseMadeAppeals::
	.string "Worsens the\n"
	.string "condition of\n"
	.string "those that\n"
	.string "made appeals.$"

gText_FourLine_BadlyStartleMonsGoodCondition::
	.string "Badly startles\n"
	.string "POKéMON in\n"
	.string "good condition.$"

gText_FourLine_AppealGreatIfPerformedFirst::
	.string "The appeal works\n"
	.string "great if\n"
	.string "performed first.$"

gText_FourLine_AppealGreatIfPerformedLast::
	.string "The appeal works\n"
	.string "great if\n"
	.string "performed last.$"

gText_FourLine_AppealAsGoodAsThoseBeforeIt::
	.string "Makes the appeal\n"
	.string "as good as\n"
	.string "those before it.$"

gText_FourLine_AppealAsGoodAsOneBeforeIt::
	.string "Makes the appeal\n"
	.string "as good as the\n"
	.string "one before it.$"

gText_FourLine_AppealBetterLaterItsPerformed::
	.string "The appeal\n"
	.string "works better\n"
	.string "the later\n"
	.string "it is performed.$"

gText_FourLine_AppealVariesDependingOnTiming::
	.string "The appeal's\n"
	.string "quality varies\n"
	.string "depending on\n"
	.string "its timing.$"

gText_FourLine_WorksWellIfSameTypeAsBefore::
	.string "Works well if\n"
	.string "it's the same\n"
	.string "type as the\n"
	.string "one before.$"

gText_FourLine_WorksWellIfDifferentTypeAsBefore::
	.string "Works well if\n"
	.string "different in\n"
	.string "type than the\n"
	.string "one before.$"

gText_FourLine_AffectedByAppealInFront::
	.string "Affected by\n"
	.string "how well the\n"
	.string "appeal in\n"
	.string "front goes.$"

gText_FourLine_UpsConditionHelpsPreventNervousness::
	.string "Ups the\n"
	.string "user's condition.\n"
	.string "Helps prevent\n"
	.string "nervousness.$"

gText_FourLine_AppealWorksWellIfConditionGood::
	.string "The appeal works\n"
	.string "well if the\n"
	.string "user's condition\n"
	.string "is good.$"

gText_FourLine_NextAppealMadeEarlier::
	.string "The next appeal\n"
	.string "can be\n"
	.string "made earlier\n"
	.string "next turn.$"

gText_FourLine_NextAppealMadeLater::
	.string "The next appeal\n"
	.string "can be\n"
	.string "made later\n"
	.string "next turn.$"

gText_FourLine_TurnOrderMoreEasilyScrambled::
	.string "Makes the next\n"
	.string "turn's order\n"
	.string "more easily\n"
	.string "scrambled.$"

gText_FourLine_ScrambleOrderOfNextAppeals::
	.string "Scrambles the\n"
	.string "order of\n"
	.string "appeals on\n"
	.string "the next turn.$"

gText_FourLine_AppealExcitesAudienceInAnyContest::
	.string "An appeal that\n"
	.string "excites the\n"
	.string "audience in\n"
	.string "any CONTEST.$"

gText_FourLine_BadlyStartlesMonsGoodAppeals::
	.string "Badly startles\n"
	.string "all POKéMON\n"
	.string "that made\n"
	.string "good appeals.$"

gText_FourLine_AppealBestMoreCrowdExcited::
	.string "The appeal\n"
	.string "works best the\n"
	.string "more the crowd\n"
	.string "is excited.$"

gText_FourLine_TemporarilyStopCrowdExcited::
	.string "Temporarily\n"
	.string "stops the\n"
	.string "crowd from\n"
	.string "growing excited.$"
#endif

@ Unused move names

gText_RainDance::
	.string "Rain Dance$"

gText_Rage::
	.string "Rage$"

gText_FocusEnergy::
	.string "Focus Energy$"

gText_Hypnosis::
	.string "Hypnosis$"

gText_Softboiled::
	.string "Softboiled$"

gText_HornAttack::
	.string "Horn Attack$"

gText_SwordsDance::
	.string "Swords Dance$"

gText_Conversion::
	.string "Conversion$"

gText_SunnyDay::
	.string "Sunny Day$"

gText_Rest2::
	.string "Rest$"

gText_Vicegrip::
	.string "Vicegrip$"

gText_DefenseCurl::
	.string "Defense Curl$"

gText_LockOn::
	.string "Lock-On$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "Cool$"

gContestMoveTypeBeautyText::
	.string "Beauty$"

gContestMoveTypeCuteText::
	.string "Cute$"

gContestMoveTypeSmartText::
	.string "Smart$"

gContestMoveTypeToughText::
	.string "Tough$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "Which move will be played?$"

gText_AppealNumButItCantParticipate::
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "But it can't participate!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} appealed with\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} was watching\n"
	.string "the others.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "We're all out of\n"
	.string "Appeal Time!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "But the appeal was\n"
	.string "jammed.$"

gText_FollowedAnotherMonsLead::
	.string "It followed another\n"
	.string "Pokémon's lead.$"

gText_ButItMessedUp::
	.string "But it messed up.$"

gText_WentBetterThanUsual::
	.string "It went better than\n"
	.string "usual.$"

gText_JudgeLookedAwayForSomeReason::
	.string "The Judge looked away\n"
	.string "for some reason.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "It worked hard to build on\n"
	.string "past mistakes.$"

gText_CantMakeAnyMoreMoves::
	.string "It can't make any more\n"
	.string "moves.$"

gText_WorkedFrighteninglyWell::
	.string "It worked frighteningly\n"
	.string "well.$"

gText_WorkedHardAsStandoutMon::
	.string "It worked as hard as the\n"
	.string "standout Pokémon.$"

gText_JudgedLookedOnExpectantly::
	.string "The Judge looked on\n"
	.string "expectantly.$"

gText_WorkedRatherWell::
	.string "It worked rather well.$"

gText_WorkedLittleBetterThanUsual::
	.string "It worked a little better\n"
	.string "than usual.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} failed to\n"
	.string "stand out at all…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} didn't stand\n"
	.string "out very much…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} caught a\n"
	.string "little attention.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} attracted a\n"
	.string "lot of attention.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} commanded\n"
	.string "total attention.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} hasn't made\n"
	.string "its appeal.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "The Judge 's views on\n"
	.string "{STR_VAR_1} held firm.$"

gText_MonsXChangedPerceptions::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "changed perceptions.$"

gText_MonsAppealEffectWoreOff::
	.string "{STR_VAR_1}'s appeal\n"
	.string "effect wore off.$"

gText_SpecialAppealsEffectWoreOff::
	.string "The special appeal's\n"
	.string "effect wore off.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Everyone's appeals were\n"
	.string "made to look the same.$"

gText_CheapenedMonsAppeal::
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_CheapenedAppealOfThoseAhead::
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_StoleAttentionAwayFromMon::
	.string "It stole attention away\n"
	.string "from {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "It severely cheapened\n"
	.string "other appeals.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "It cheapened the Judge's\n"
	.string "favorite appeal.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "The appeals of others\n"
	.string "were cheapened by half.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "It stood out to make up\n"
	.string "for being jammed.$"

gText_CantParticipateInAppealsAnyMore::
	.string "It can't participate in\n"
	.string "appeals any more.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "It touched the Judge for\n"
	.string "a fantastic appeal.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Anticipation rose for\n"
	.string "upcoming appeals.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "It stood out as much as\n"
	.string "special appeals.$"

gText_StoodOutAsMuchAsMon::
	.string "It stood out as much as\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Jammed appeals were made\n"
	.string "even less noticeable.$"

gText_EveryonesAppealsMadeSame::
	.string "Everyone's appeals were\n"
	.string "made the same.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "It became more conscious\n"
	.string "of the other Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} can't make an\n"
	.string "appeal after this.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "It settled down just a\n"
	.string "little bit.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "It became oblivious to\n"
	.string "the other Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "It became less aware of\n"
	.string "the other Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "It stopped caring about\n"
	.string "other Pokémon much.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "It tried to startle the\n"
	.string "other Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "It tried to dazzle the\n"
	.string "others.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "The Judge looked away\n"
	.string "from {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "It tried to unnerve the\n"
	.string "next Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} became\n"
	.string "nervous.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "The appeal tried to\n"
	.string "unnerve waiting Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "It taunted Pokémon\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} regained its\n"
	.string "form.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "It tried to jam Pokémon\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "The standout {STR_VAR_1}\n"
	.string "hustled even more.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "The largely unnoticed\n"
	.string "{STR_VAR_1} worked hard.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "It worked as much as\n"
	.string "Pokémon before it.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "It worked as much as the\n"
	.string "preceding Pokémon.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{STR_VAR_1}'s appeal was\n"
	.string "a dud.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not work very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "It's the same type as the\n"
	.string "Pokémon before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "It's not the same type as\n"
	.string "the one before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "It stood out much more\n"
	.string "than the Pokémon before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "It didn't do as well as the\n"
	.string "Pokémon before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{STR_VAR_1}'s condition\n"
	.string "rose above usual.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{STR_VAR_1}'s hot status\n"
	.string "made it a great appeal!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "It moved up in line for\n"
	.string "the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "It moved back in line once\n"
	.string "for the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "It scrambled up the\n"
	.string "order for the next turn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "The Judge looked at\n"
	.string "{STR_VAR_1} expectantly.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "The appeal combo went\n"
	.string "over well.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "The appeal combo went\n"
	.string "over very well.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "The appeal combo went\n"
	.string "over excellently.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} managed to\n"
	.string "avert its gaze.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} managed to\n"
	.string "avoid seeing it.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} isn't fazed\n"
	.string "by that sort of thing.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} became a\n"
	.string "little distracted.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "It tried to startle the\n"
	.string "other Pokémon.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} looked down\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} turned back\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} couldn't help\n"
	.string "uttering a cry.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} couldn't help\n"
	.string "leaping up.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} tripped over\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} was too\n"
	.string "nervous to move.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "But it messed up.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "But it failed to make\n"
	.string "the target nervous.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "But it failed to make\n"
	.string "anyone nervous.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "But it was ignored…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "But it couldn't improve\n"
	.string "its condition…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Its bad condition\n"
	.string "resulted in a weak appeal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} was\n"
	.string "unaffected.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} disappointed\n"
	.string "by repeating an appeal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "went over great.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "didn't go over well here…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "got the crowd going.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} can't appeal\n"
	.string "next turn…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "It attracted the crowd's\n"
	.string "attention.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "The crowd continues to\n"
	.string "watch {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}'s\n"
	.string "{STR_VAR_2} is ignored.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "shyness$"

gText_Contest_Anxiety::
	.string "anxiety$"

gText_Contest_Laziness::
	.string "laziness$"

gText_Contest_Hesitancy::
	.string "hesitancy$"

gText_Contest_Fear::
	.string "fear$"

gText_Contest_Coolness::
	.string "coolness$"

gText_Contest_Beauty::
	.string "beauty$"

gText_Contest_Cuteness::
	.string "cuteness$"

gText_Contest_Smartness::
	.string "smartness$"

gText_Contest_Toughness::
	.string "toughness$"

@ Unused
gText_Tension::
	.string "Tension$"

gText_CoolMove::
	.string "Cool Move$"

gText_BeautyMove::
	.string "Beauty Move$"

gText_CuteMove::
	.string "Cute Move$"

gText_SmartMove::
	.string "Smart Move$"

gText_ToughMove::
	.string "Tough Move$"

gText_3QuestionMarks::
	.string "???$"
