@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "Resulta muy llamativo.$"

gText_UserMoreEasilyStartled::
	.string "Tras usarlo, será facil\nque te asusten.$"

gText_GreatAppealButNoMoreToEnd::
	.string "Gusta mucho, pero impide\nseguir participando.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Por más que se use, el JUEZ\nno se aburrirá nunca.$"

gText_AvoidStartledByOthersOnce::
	.string "Puede evitar que\nte asusten una vez.$"

gText_AvoidStartledByOthers::
	.string "Puede evitar\nque te asusten.$"

gText_AvoidStartledByOthersLittle::
	.string "Can avoid being startled\nby others a little.$"

gText_UserLessLikelyStartled::
	.string "After this move, the user is\nless likely to be startled.$"

gText_SlightlyStartleFrontMon::
	.string "Slightly startles the\nPOKéMON in front.$"

gText_SlightlyStartleAppealed::
	.string "Slightly startles those\nthat have made appeals.$"

gText_StartleAppealedBeforeUser::
	.string "Asusta al POKéMON que se\nha exhibido antes que tú.$"

gText_StartleAllAppealed::
	.string "Asusta a los POKéMON que\nya se han exhibido.$"

gText_BadlyStartleFrontMon::
	.string "Aterra al último POKéMON\nque se exhibió.$"

gText_BadlyStartleAppealed::
	.string "Aterra a los que\nya se han exhibido.$"

gText_StartleAppealedBeforeUser2::
	.string "Asusta al POKéMON que se\nha exhibido antes que tú.$"

gText_StartleAllAppealed2::
	.string "Asusta a los POKéMON que\nya se han exhibido.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Hace que el JUEZ deje de\nprestar atención al resto.$"

gText_StartleMonHasJudgesAttention::
	.string "Asusta más al POKéMON que\ncapta la atención del JUEZ.$"

gText_JamOthersMissesTurn::
	.string "Inhibe a los otros,\npero pierdes un turno.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Asusta más a los que usaron\nrecursos del mismo tipo.$"

gText_BadlyStartleCoolAppeals::
	.string "Badly startles POKéMON\nthat made COOL appeals.$"

gText_BadlyStartleBeautyAppeals::
	.string "Badly startles POKéMON\nthat made BEAUTY appeals.$"

gText_BadlyStartleCuteAppeals::
	.string "Badly startles POKéMON\nthat made CUTE appeals.$"

gText_BadlyStartleSmartAppeals::
	.string "Badly startles POKéMON\nthat made SMART appeals.$"

gText_BadlyStartleToughAppeals::
	.string "Badly startles POKéMON\nthat made TOUGH appeals.$"

gText_MakeMonAfterUserNervous::
	.string "Makes one POKéMON after\nthe user nervous.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Inquieta a los POKéMON\nque van detrás de ti.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Baja la forma de los que\nse han exhibido.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Badly startles POKéMON in\ngood condition.$"

gText_AppealGreatIfPerformedFirst::
	.string "La exhibición es un éxito\nsi se es el primero.$"

gText_AppealGreatIfPerformedLast::
	.string "La exhibición es un éxito\nsi se es el ultimo.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "La exhibición es tan buena\ncomo las anteriores.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "La exhibición es tan buena\ncomo la anterior.$"

gText_AppealBetterLaterItsPerformed::
	.string "Causa mayor impacto cuanto\nmás tarde se usa.$"

gText_AppealVariesDependingOnTiming::
	.string "El impacto que tenga varía\nsegún cuándo se use.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Funciona bien si es del\nmismo tipo que el anterior.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Works well if different in\ntype than the one before.$"

gText_AffectedByAppealInFront::
	.string "El éxito dependerá de la\nactuación precedente.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Mejora tu forma y te ayuda\na mantener la calma.$"

gText_AppealWorksWellIfConditionGood::
	.string "Resulta muy lucido\nsi estás en buena forma.$"

gText_NextAppealMadeEarlier::
	.string "En la siguiente ronda, deja\nque te exhibas antes.$"

gText_NextAppealMadeLater::
	.string "En la siguiente ronda, deja\nque te exhibas más tarde.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Makes the next turn's order\nmore easily scrambled.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Altera los turnos en la\nsiguiente ronda.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "Entusiasma al público\nen cualquier CONCURSO.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Aterra a todos los POKéMON\nque se han exhibido bien.$"

gText_AppealBestMoreCrowdExcited::
	.string "El lucimiento es mayor si\nel público está entregado.$"

gText_TemporarilyStopCrowdExcited::
	.string "Templa momentáneamente\nel fervor del público.$"

@ Unused move names

gText_RainDance::
	.string "RAIN DANCE$"

gText_Rage::
	.string "RAGE$"

gText_FocusEnergy::
	.string "FOCUS ENERGY$"

gText_Hypnosis::
	.string "HYPNOSIS$"

gText_Softboiled::
	.string "SOFTBOILED$"

gText_HornAttack::
	.string "HORN ATTACK$"

gText_SwordsDance::
	.string "SWORDS DANCE$"

gText_Conversion::
	.string "CONVERSION$"

gText_SunnyDay::
	.string "SUNNY DAY$"

gText_Rest2::
	.string "REST$"

gText_Vicegrip::
	.string "VICEGRIP$"

gText_DefenseCurl::
	.string "DEFENSE CURL$"

gText_LockOn::
	.string "LOCK-ON$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "COOL$"

gContestMoveTypeBeautyText::
	.string "BEAUTY$"

gContestMoveTypeCuteText::
	.string "CUTE$"

gContestMoveTypeSmartText::
	.string "SMART$"

gContestMoveTypeToughText::
	.string "TOUGH$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "Which move will be played?$"

gText_AppealNumButItCantParticipate::
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "But it can't participate!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} appealed with\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} was watching\n"
	.string "the others.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "We're all out of\n"
	.string "Appeal Time!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "But the appeal was\n"
	.string "jammed.$"

gText_FollowedAnotherMonsLead::
	.string "It followed another\n"
	.string "POKéMON's lead.$"

gText_ButItMessedUp::
	.string "But it messed up.$"

gText_WentBetterThanUsual::
	.string "It went better than\n"
	.string "usual.$"

gText_JudgeLookedAwayForSomeReason::
	.string "The JUDGE looked away\n"
	.string "for some reason.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "It worked hard to build on\n"
	.string "past mistakes.$"

gText_CantMakeAnyMoreMoves::
	.string "It can't make any more\n"
	.string "moves.$"

gText_WorkedFrighteninglyWell::
	.string "It worked frighteningly\n"
	.string "well.$"

gText_WorkedHardAsStandoutMon::
	.string "It worked as hard as the\n"
	.string "standout POKéMON.$"

gText_JudgedLookedOnExpectantly::
	.string "The JUDGE looked on\n"
	.string "expectantly.$"

gText_WorkedRatherWell::
	.string "It worked rather well.$"

gText_WorkedLittleBetterThanUsual::
	.string "It worked a little better\n"
	.string "than usual.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} failed to\n"
	.string "stand out at all…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} didn't stand\n"
	.string "out very much…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} caught a\n"
	.string "little attention.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} attracted a\n"
	.string "lot of attention.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} commanded\n"
	.string "total attention.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} hasn't made\n"
	.string "its appeal.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "The JUDGE 's views on\n"
	.string "{STR_VAR_1} held firm.$"

gText_MonsXChangedPerceptions::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "changed perceptions.$"

gText_MonsAppealEffectWoreOff::
	.string "{STR_VAR_1}'s appeal\n"
	.string "effect wore off.$"

gText_SpecialAppealsEffectWoreOff::
	.string "The special appeal's\n"
	.string "effect wore off.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Everyone's appeals were\n"
	.string "made to look the same.$"

gText_CheapenedMonsAppeal::
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_CheapenedAppealOfThoseAhead::
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_StoleAttentionAwayFromMon::
	.string "It stole attention away\n"
	.string "from {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "It severely cheapened\n"
	.string "other appeals.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "It cheapened the JUDGE's\n"
	.string "favorite appeal.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "The appeals of others\n"
	.string "were cheapened by half.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "It stood out to make up\n"
	.string "for being jammed.$"

gText_CantParticipateInAppealsAnyMore::
	.string "It can't participate in\n"
	.string "appeals any more.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "It touched the JUDGE for\n"
	.string "a fantastic appeal.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Anticipation rose for\n"
	.string "upcoming appeals.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "It stood out as much as\n"
	.string "special appeals.$"

gText_StoodOutAsMuchAsMon::
	.string "It stood out as much as\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Jammed appeals were made\n"
	.string "even less noticeable.$"

gText_EveryonesAppealsMadeSame::
	.string "Everyone's appeals were\n"
	.string "made the same.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "It became more conscious\n"
	.string "of the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} can't make an\n"
	.string "appeal after this.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "It settled down just a\n"
	.string "little bit.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "It became oblivious to\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "It became less aware of\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "It stopped caring about\n"
	.string "other POKéMON much.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "It tried to startle the\n"
	.string "other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "It tried to dazzle the\n"
	.string "others.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "The JUDGE looked away\n"
	.string "from {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "It tried to unnerve the\n"
	.string "next POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} became\n"
	.string "nervous.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "The appeal tried to\n"
	.string "unnerve waiting POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "It taunted POKéMON\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} regained its\n"
	.string "form.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "It tried to jam POKéMON\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "The standout {STR_VAR_1}\n"
	.string "hustled even more.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "The largely unnoticed\n"
	.string "{STR_VAR_1} worked hard.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "It worked as much as\n"
	.string "POKéMON before it.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "It worked as much as the\n"
	.string "preceding POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{STR_VAR_1}'s appeal was\n"
	.string "a dud.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not work very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "It's the same type as the\n"
	.string "POKéMON before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "It's not the same type as\n"
	.string "the one before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "It stood out much more\n"
	.string "than the POKéMON before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "It didn't do as well as the\n"
	.string "POKéMON before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{STR_VAR_1}'s condition\n"
	.string "rose above usual.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{STR_VAR_1}'s hot status\n"
	.string "made it a great appeal!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "It moved up in line for\n"
	.string "the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "It moved back in line once\n"
	.string "for the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "It scrambled up the\n"
	.string "order for the next turn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "The JUDGE looked at\n"
	.string "{STR_VAR_1} expectantly.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "The appeal combo went\n"
	.string "over well.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "The appeal combo went\n"
	.string "over very well.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "The appeal combo went\n"
	.string "over excellently.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} managed to\n"
	.string "avert its gaze.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} managed to\n"
	.string "avoid seeing it.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} isn't fazed\n"
	.string "by that sort of thing.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} became a\n"
	.string "little distracted.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "It tried to startle the\n"
	.string "other POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} looked down\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} turned back\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} couldn't help\n"
	.string "uttering a cry.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} couldn't help\n"
	.string "leaping up.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} tripped over\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} was too\n"
	.string "nervous to move.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "But it messed up.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "But it failed to make\n"
	.string "the target nervous.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "But it failed to make\n"
	.string "anyone nervous.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "But it was ignored…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "But it couldn't improve\n"
	.string "its condition…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Its bad condition\n"
	.string "resulted in a weak appeal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} was\n"
	.string "unaffected.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} disappointed\n"
	.string "by repeating an appeal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "went over great.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "didn't go over well here…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "got the crowd going.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} can't appeal\n"
	.string "next turn…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "It attracted the crowd's\n"
	.string "attention.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "The crowd continues to\n"
	.string "watch {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}'s\n"
	.string "{STR_VAR_2} is ignored.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "shyness$"

gText_Contest_Anxiety::
	.string "anxiety$"

gText_Contest_Laziness::
	.string "laziness$"

gText_Contest_Hesitancy::
	.string "hesitancy$"

gText_Contest_Fear::
	.string "fear$"

gText_Contest_Coolness::
	.string "coolness$"

gText_Contest_Beauty::
	.string "beauty$"

gText_Contest_Cuteness::
	.string "cuteness$"

gText_Contest_Smartness::
	.string "smartness$"

gText_Contest_Toughness::
	.string "toughness$"

@ Unused
gText_Tension::
	.string "TENSION$"

gText_CoolMove::
	.string "COOL Move$"

gText_BeautyMove::
	.string "BEAUTY Move$"

gText_CuteMove::
	.string "CUTE Move$"

gText_SmartMove::
	.string "SMART Move$"

gText_ToughMove::
	.string "TOUGH Move$"

gText_3QuestionMarks::
	.string "???$"
