Text_BootUpPC:
	.string "{PLAYER} encendió el PC.$"

gText_WhichPCShouldBeAccessed::
	.string "¿A qué PC quieres acceder?$"

gText_AccessedSomeonesPC::
	.string "Accedido al PC de alguien.$"

gText_StorageSystemOpened::
	.string "Ingresado al Sistema de Almacenamiento\n"
	.string "de Pokémon.$"

gText_AccessedPlayersPC::
	.string "Accedido al PC de {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Accedido al PC de Aredia.$"
