#if GAME_LANGUAGE == LANGUAGE_SPANISH
Text_BootUpPC:
	.string "{PLAYER} encendió el PC.$"

gText_WhichPCShouldBeAccessed::
	.string "¿A qué PC quieres acceder?$"

gText_AccessedSomeonesPC::
	.string "Accedido al PC de alguien.$"

gText_StorageSystemOpened::
	.string "Ingresado al Sistema de Almacenamiento\n"
	.string "de Pokémon.$"

gText_AccessedPlayersPC::
	.string "Accedido al PC de {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Accedido al PC de Aredia.$"
#else
Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed Someone's PC.$"

gText_StorageSystemOpened::
	.string "Pokémon Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Accessed Lanette's PC.$"
#endif
