gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} fue enviado al PC\n"
	.string "de alguien.\p"
	.string "Se ha guardado en la Caja\n"
	.string "“{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} fue enviado al PC\nde Aredia.\p"
	.string "Se ha guardado en la Caja\n"
	.string "“{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La Caja “{STR_VAR_3}” del PC\n"
	.string "de alguien estaba llena.\p"
	.string "{STR_VAR_2} fue enviado a la Caja\n"
	.string "“{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "La Caja “{STR_VAR_3}” del PC\n"
	.string "de Aredia estaba llena.\p"
	.string "{STR_VAR_2} fue enviado a la Caja\n"
	.string "“{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
	.string "¡No queda sitio para más Pokémon!\p"
	.string "¡Las Cajas Pokémon están llenas!$"

gText_NicknameThisPokemon::
	.string "Do you want to give a nickname to\n"
	.string "this {STR_VAR_1}?$"
