#if GAME_LANGUAGE == LANGUAGE_SPANISH
gText_PkmnCenterJack_Nickname::
    .string "Nickname$"
gText_PkmnCenterJack_Remember::
    .string "Remember$"
gText_PkmnCenterJack_Forget::
    .string "Forget$"
gText_PkmnCenterJack_Teach::
    .string "Teach$"
#else
gText_PkmnCenterJack_Nickname::
    .string "Nickname$"
gText_PkmnCenterJack_Remember::
    .string "Remember$"
gText_PkmnCenterJack_Forget::
    .string "Forget$"
gText_PkmnCenterJack_Teach::
    .string "Teach$"
#endif
