#if GAME_LANGUAGE == LANGUAGE_SPANISH
gText_PkmnCenterJack_GotPokemonQuestions::
    .string "Got some Pokémon questions?\n"
    .string "Feel free to ask away.$"
gText_PkmnCenterJack_Nickname::
    .string "Nickname$"
gText_PkmnCenterJack_Remember::
    .string "Remember$"
gText_PkmnCenterJack_Forget::
    .string "Forget$"
gText_PkmnCenterJack_Teach::
    .string "Teach$"
gText_PkmnCenterJack_ComeBackAnytime::
    .string "Well, come back anytime.$"
#else
gText_PkmnCenterJack_GotPokemonQuestions::
    .string "Got some Pokémon questions?\n"
    .string "Feel free to ask away.$"
gText_PkmnCenterJack_Nickname::
    .string "Nickname$"
gText_PkmnCenterJack_Remember::
    .string "Remember$"
gText_PkmnCenterJack_Forget::
    .string "Forget$"
gText_PkmnCenterJack_Teach::
    .string "Teach$"
gText_PkmnCenterJack_ComeBackAnytime::
    .string "Well, come back anytime.$"
#endif
