	.align 2
gText_ConfirmSave::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOff::
	.string "Guardando…\n"
	.string "No apagues la consola.$"

gText_PlayerSavedGame::
	.string "{PLAYER} guardó la partida.$"

gText_DifferentSaveFile::
	.string "¡ATENCIÓN!\p"
	.string "Ya hay una partida guardada.\p"
	.string "Si guardas, perderás los datos\n"
	.string "de la partida incluyendo los\l"
	.string "objetos y los Pokémon.\p"
	.string "¿Seguro que quieres guardar ahora\n"
	.string "y sobrescribir los otros datos?$"

gText_SaveError::
	.string "Error al guardar.\p"
	.string "Por favor cambie la\n"
	.string "memoria de respaldo.$"

gText_SavingDontTurnOffPower::
	.string "Guardando…\n"
	.string "No apagues la consola.$"
