#if GAME_LANGUAGE == LANGUAGE_SPANISH
gText_WantToUseSurf::
	.string "El agua tiene buena pinta…\n"
	.string "¿Quieres hacer Surf?$"

Text_ExploudSurf::
	.string "El agua tiene buena pinta…\n"
	.string "¿Llamas al Exploud de Papá?$"

gText_PlayerUsedSurf::
	.string "¡{STR_VAR_1} usó Surf!$"
#else
gText_WantToUseSurf::
	.string "The water is dyed a deep blue…\n"
	.string "Would you like to Surf?$"

Text_ExploudSurf::
	.string "The water is dyed a deep blue…\n"
	.string "Call Dad's Exploud to Surf?$"

gText_PlayerUsedSurf::
	.string "{STR_VAR_1} used Surf!$"
#endif
