#if GAME_LANGUAGE == LANGUAGE_SPANISH
gText_WantToUseSurf::
	.string "El agua tiene buena pinta…\n¿Quieres hacer Surf?$"

Text_ExploudSurf::
	.string "El agua tiene buena pinta…\n¿Llamas al Exploud de Papá?$"

gText_PlayerUsedSurf::
	.string "¡{STR_VAR_1} usó Surf!$"
#else
gText_WantToUseSurf::
	.string "The water is dyed a deep blue…\nWould you like to Surf?$"

Text_ExploudSurf::
	.string "The water is dyed a deep blue…\nCall Dad's Exploud to Surf?$"

gText_PlayerUsedSurf::
	.string "{STR_VAR_1} used Surf!$"
#endif
